### ISSUE TITLE
Rug Pulls Put 2021 Scam Revenue Close to All-time Highs

### ISSUE THREAD

**Issue by nurkiewicz** [nurkiewicz/crypto-hall-of-shame#34]
https://blog.chainalysis.com/reports/2021-crypto-scam-revenues/

**Comment by hackmistress69** [comment]
![6348CF2C-1201-4DCC-83D9-B54C5683406A](https://user-images.githubusercontent.com/106688202/184520489-f094db7e-00cf-49d7-b958-8ea465a81b42.jpeg)
